Adding aliases to Elasticsearch indices

diff --git a/bin/elastic b/bin/elastic
--- a/bin/elastic
+++ b/bin/elastic
@@ -12,6 +12,7 @@ Commands:
   $(tput smul)index list$(tput rmul) [pattern]         - list all indices or matching optional pattern
   $(tput smul)index delete$(tput rmul) [pattern]       - delete indices matching pattern
   $(tput smul)index add-mapping$(tput rmul) index json - add new field to existing index
+  $(tput smul)index add-alias$(tput rmul) index alias  - add new alias to existing index
 
 Options:
   -c, --cluster                - Elasticsearch cluster URL, http://localhost:9200 is default
@@ -111,6 +112,20 @@ function index_add_mapping() {
   fi
 
   put $index/_mapping -d "$json"
+}
+
+function index_add_alias() {
+  index="$1"
+  alias="$2"
+
+  if [[ -z $alias ]]; then
+    echo "alias argument is required"
+    exit 1
+  fi
+
+  json='{"actions": {"add": {"index": "'$index'", "alias": "'$alias'"}}}'
+
+  post _aliases -d "$json"
 }
 
 CURL="curl --silent"
